[package]
name = "livekit-api"
version = "0.4.1"
license = "Apache-2.0"
description = "Rust Server SDK for LiveKit"
edition = "2021"
repository = "https://github.com/livekit/rust-sdks"

[features]
# By default ws TLS is not enabled
default = ["services-tokio", "webhooks"]

signal-client-tokio = [
    "dep:tokio-tungstenite",
    "dep:tokio",
    "dep:futures-util",
    "dep:reqwest",
    "dep:livekit-runtime",
    "livekit-runtime/tokio",
]

signal-client-async = [
    "dep:async-tungstenite",
    "dep:tokio",             # For macros and sync
    "dep:futures-util",
    "dep:isahc",
    "dep:livekit-runtime",
    "livekit-runtime/async",
]

signal-client-dispatcher = [
    "dep:async-tungstenite",
    "dep:tokio",                  # For macros and sync
    "dep:futures-util",
    "dep:livekit-runtime",
    "livekit-runtime/dispatcher",
    "dep:serde_json",
]

services-tokio = ["dep:reqwest"]
services-dispatcher = ["dep:serde_json"]
services-async = ["dep:isahc"]
webhooks = ["dep:serde_json", "dep:base64"]

# Deprecated: old feature that does nothing.
access-token = []

# Note that the following features only change the behavior of tokio-tungstenite.
# It doesn't change the behavior of libwebrtc/webrtc-sys
native-tls = [
    "tokio-tungstenite?/native-tls",
    "async-tungstenite?/async-native-tls",
    "reqwest?/native-tls",
]
native-tls-vendored = [
    "tokio-tungstenite?/native-tls-vendored",
    "reqwest?/native-tls-vendored",
]
rustls-tls-native-roots = [
    "tokio-tungstenite?/rustls-tls-native-roots",
    "async-tungstenite?/async-tls",
    "reqwest?/rustls-tls-native-roots",
]
rustls-tls-webpki-roots = [
    "tokio-tungstenite?/rustls-tls-webpki-roots",
    "reqwest?/rustls-tls-webpki-roots",
]
__rustls-tls = ["tokio-tungstenite?/__rustls-tls", "reqwest?/__rustls"]

[dependencies]
livekit-protocol = { path = "../livekit-protocol", version = "0.3.6" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
url = "2.3"
log = "0.4"
parking_lot = { version = "0.12" }
prost = "0.12"

# webhooks
serde_json = { version = "1.0", optional = true }
base64 = { version = "0.21", optional = true }

# access_token & services
http = "0.2.1"
scopeguard = "1.2.0"

[dependencies.jsonwebtoken]
version = "9"
default-features = false

[dependencies.livekit-runtime]
version = "0.3.0"
path = "../livekit-runtime"
optional = true

[dependencies.tokio-tungstenite]
version = "0.20"
optional = true

[dependencies.async-tungstenite]
optional = true
version = "0.28"
features = ["async-std-runtime", "async-tls"]

[dependencies.futures-util]
version = "0.3"
default-features = false
features = ["sink"]
optional = true

[dependencies.tokio]
version = "1"
default-features = false
features = ["sync", "macros", "signal"]
optional = true

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json"]
optional = true

[dependencies.isahc]
features = ["json", "text-decoding"]
optional = true
version = "1.7.2"
default-features = false
